code/lvmeng_project-master/lvmeng/urls.py
from django.conf.urls import include, url,handler404,handler500
from django.contrib import admin
from django.conf.urls.static import static
from lvmeng import settings
from django.views.generic.base import RedirectView
from django.views.decorators.csrf import csrf_exempt
from rest_framework.authtoken import views
from erp import views2
import web_customer.views
from erp.tests import test_login

handler404 = "erp.views.page_not_found"
handler500 = "erp.views.page_error"


urlpatterns = [
    #admin
    url(r'admin/', include(admin.site.urls)),

    #homepage
    url(r'^$', web_customer.views.homePage),
    url(r'^ie8', web_customer.views.homePage_ie8),
    url(r'^mobi/$', web_customer.views.mobile_homePage),

    #login
    url(r'customer_login/$', web_customer.views.customer_login),
    url(r'login/$', views2.account_login),

    url(r'test/$', test_login),#test for login

    #inner app
    url(r'^api/', include('api.urls')),
    url(r'^agent_api/', include('agent_api.urls')),
    url(r'^message_api/', include('message_api.urls')),
    url(r'^push/', include('push.urls')),
    url(r'^erp/', include('erp.urls')),
    url(r'^oa/', include('oa.urls')),
    url(r'^web_customer/', include('web_customer.urls')),
    url(r'^mobi/', include('mobi.urls')),
    url(r'^invest/', include('investment.urls')),

    #outer app
    url(r'^tinymce/',include('tinymce.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),#TODO:need to remove csrf_exempt in production
    # url(r'^rest-auth/', include('rest_auth.urls')),
    url(r'^api-token-auth/', views.obtain_auth_token),
    url(r'^captcha/', include('captcha.urls')),

    #account
    # url(r'^password_change/', 'django.contrib.auth.views.password_change', {'post_change_redirect': '/password_change_done/'}),
    url(r'^password_change/', 'django.contrib.auth.views.password_change', {'post_change_redirect': '/'}),
    url(r'^password_change_done/', 'django.contrib.auth.views.password_change_done'),
    # url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/accounts/login/'}),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
    url(r'^accounts/', include('registration.backends.default.urls')),

    # url(r'admin/', include(admin.site.urls)),
    # url(r'^$', include('web_customer.urls')),
    # url(r'^web_customer/', include('web_customer.urls')),
    # url(r'^mobi/$', web_customer.views.mobile_homePage),
    # url(r'^announcement/$', web_customer.views.announcement),
    # url(r'^tinymce/',include('tinymce.urls')),
]

#todo has to be removed in production
#this will serve media files during development environment, otherwise files uploaded by users won't be recognized
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

code/lvmeng_project-master/oa/urls.py
#coding:utf-8
#employee_distribution

from django.conf.urls import url
from . import views,views2

urlpatterns = [
    url(r'^employee_distribution/$', views.employee_distribution),#
    url(r'^employee_position/$', views.employee_position),#
    url(r'^ajax_name/$', views.ajax_name),#根据ID获取姓名
    url(r'^employee_history_position/$', views.employee_history_position),#根据ID获取姓名
    url(r'^employee_history_position_days/$', views.employee_history_position_days),#根据ID获取姓名

    url(r'^announcement_employee/$', views.announcement_employee),#通知公告(面向员工)
    url(r'^announcement_add_modify/$', views.announcement_add_modify),#通知公告新增/修改/

    url(r'^daily_work/$', views.daily_work),#工作汇报列表/删除
    url(r'^daily_work_add_modify/$', views.daily_work_add_modify),#工作汇报新增/

    url(r'^cost_application/$', views.cost_application),#费用列表和删除
    url(r'^cost_add_modify/$', views.cost_add_modify),#费用新增
    url(r'^edit_examine/$', views.edit_examine),#编写费用审核
    url(r'^cost_examine/$', views2.cost_examine),#查看费用审核结果
    url(r'^daily_work_examine/$', views2.daily_work_examine),#查看工作汇报审核结果
    url(r'^examine_list/$', views2.examine_list),#查看自己的所有审核列表

    url(r'^leave_management/$', views.leave_management),#请假列表和删除
    url(r'^leave_add_modify/$', views.leave_add_modify),#请假新增
    # url(r'^edit_leave_examine/$', views.edit_leave_examine),#编写请假审核
    url(r'^leave_examine/$', views2.leave_examine),#查看请假审核结果
    # url(r'^leave_examine_list/$', views2.leave_examine_list),#查看自己的请假审核列表

    url(r'^travel_apply/$', views.travel_apply),#出差列表和删除
    url(r'^travel_add_modify/$', views.travel_add_modify),#出差新增
    # url(r'^edit_travel_examine/$', views.edit_travel_examine),#编写出差审核
    url(r'^travel_examine/$', views2.travel_examine),#查看出差审核结果
    # url(r'^travel_examine_list/$', views2.travel_examine_list),#查看自己的出差审核列表

    url(r'^daily_todo_list/$', views2.daily_todo_list),#每日待办列表/删除
    url(r'^daily_todo_add_modify/$', views2.daily_todo_add_modify),#每日待办事件新增和修改

    url(r'^check_table/$', views2.check_table),#
    url(r'^check_time_setting/$', views2.check_time_setting),#

    # url(r'^read_message/$', views.read_message),#添加已读记录







]

code/lvmeng_project-master/push/urls.py
#! /usr/bin/env python
#coding:utf-8

from django.conf.urls import url, include
from api.rest_framework import APNSDeviceAuthorizedViewSet, GCMDeviceAuthorizedViewSet, JPUSHDeviceAuthorizedViewSet
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'device/apns', APNSDeviceAuthorizedViewSet)
router.register(r'device/gcm', GCMDeviceAuthorizedViewSet)
router.register(r'device/jpush', JPUSHDeviceAuthorizedViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),

]

code/lvmeng_project-master/oa/models.py
#coding:utf-8
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
import datetime

from api.views import points_deal
from erp.models import *

import logging
logger = logging.getLogger(__name__)

# from push.views import push_to_ios, push_to_android

# Create your models here.
type = (('1',u'签到'),('0',u'签退'))
class CheckWork(models.Model):#考勤
    check_user = models.OneToOneField(User,verbose_name=u"关联用户")
    check_business = models.ForeignKey(Business,verbose_name=u"关联机构")
    type = models.CharField(choices=type, max_length=10, default="1", verbose_name=u"签到类型")
    abscissa = models.CharField(max_length=30,verbose_name=u"横坐标")#经度
    ordinate = models.CharField(max_length=30,verbose_name=u"纵坐标")#纬度
    address = models.CharField(max_length=300,null=True,blank=True,verbose_name=u"地址")
    area = models.CharField(max_length=300,null=True,blank=True,verbose_name=u"地区")
    check_time = models.DateTimeField(verbose_name=u"考勤时间")

    def __unicode__(self):
        return self.check_user.first_name

    # def toJSON(self):
    #     import json
    #     return json.dumps(dict([(attr, getattr(self, attr)) for attr in [f.name for f in self._meta.fields]]))

class CheckWork_history(models.Model):#考勤历史
    check_history = models.ForeignKey(User,verbose_name=u"关联用户")
    check_business_history = models.ForeignKey(Business,verbose_name=u"关联机构")
    type = models.CharField(choices=type, max_length=10, default="1", verbose_name=u"签到类型")
    abscissa = models.CharField(max_length=30,verbose_name=u"横坐标")
    ordinate = models.CharField(max_length=30,verbose_name=u"纵坐标")
    address = models.CharField(max_length=300,null=True,blank=True,verbose_name=u"地址")
    area = models.CharField(max_length=300,null=True,blank=True,verbose_name=u"地区")
    check_time = models.DateTimeField(verbose_name=u"考勤时间")
    # time_now = models.TimeField(null=True,blank=True,auto_now_add=True)

    def __unicode__(self):
        return self.check_history.first_name

top_choice = (('1',u'否'),('2',u'是'))
publish_choice = (('1',u'不发布'),('2',u'发布'))
class Internal_announcement(models.Model):#通知公告(员工)

    announcement_business = models.ForeignKey(Business,verbose_name=u"所属机构")
    topic = models.CharField(max_length=30,verbose_name=u"主题")

    on_top = models.CharField(choices=top_choice,max_length=1,default="1",verbose_name=u"是否置顶")
    onTop_start = models.DateField(null=True,blank=True,verbose_name=u"置顶开始时间")
    onTop_end = models.DateField(null=True,blank=True,verbose_name=u"置顶结束时间")
    publish = models.CharField(choices=publish_choice,default="1",max_length=1,verbose_name=u"是否发布")
    publish_start = models.DateField(null=True,blank=True,verbose_name=u"发布开始时间")
    publish_end = models.DateField(null=True,blank=True,verbose_name=u"发布结束时间")
    is_active = models.BooleanField(verbose_name=u"是否有效",default=True)
    add_time = models.DateField(auto_now_add=True,verbose_name=u"添加时间")
    # content = models.TextField(max_length=300,verbose_name=u"通知内容")
    content = HTMLField(null=True,blank=True,verbose_name=u"通知内容")

    class Meta:
        ordering = ['-add_time']

daily_work_type = (('1',u'日报'),('2',u'周报'),('3',u'月报'))

class Daily_work(models.Model):#工作汇报
    business = models.ForeignKey(Business,verbose_name=u"所属机构",null=True,blank=True)
    user = models.ForeignKey(User,null=True,blank=True,verbose_name=u"填报人")
    examine_user = models.ManyToManyField(User,null=True,blank=True,verbose_name=u"审批人",related_name="daily_examine_user")
    topic = models.CharField(max_length=300,verbose_name=u"当天总结")
    content = models.CharField(max_length=300,verbose_name=u"明日计划")
    work_type = models.CharField(choices=daily_work_type,max_length=5,null=True,blank=True,default='1',verbose_name=u"工作汇报类型")
    time = models.DateTimeField(auto_now_add=True,verbose_name=u"填报时间")
    is_active = models.BooleanField(verbose_name=u"是否有效",default=True)

    class Meta:
        ordering = ['-time']

read_status = (('1',u'未读'),('2',u'已读'))
class Cost_application(models.Model):#费用申请
    business = models.ForeignKey(Business,null=True,blank=True,verbose_name=u"所属机构")
    user = models.ForeignKey(User,null=True,blank=True,verbose_name=u"申请人")
    examine_user = models.ManyToManyField(User,null=True,blank=True,verbose_name=u"审批人",related_name="cost_examine_user")
    topic = models.CharField(max_length=20,verbose_name=u"申请条目")
    content = models.CharField(max_length=100,verbose_name=u"申请内容")
    cost = models.BigIntegerField(verbose_name=u"金额(元)")
    time = models.DateTimeField(auto_now_add=True,verbose_name=u"申请时间")
    is_active = models.BooleanField(verbose_name=u"是否有效",default=True)

    class Meta:
        ordering = ['-time']


class Leave_management(models.Model):#请假管理
    business = models.ForeignKey(Business,null=True,blank=True,verbose_name=u"所属机构")
    user = models.ForeignKey(User,null=True,blank=True,verbose_name=u"请假人")
    examine_user = models.ManyToManyField(User,null=True,blank=True,verbose_name=u"审批人",related_name="leave_examine_user")
    topic = models.CharField(max_length=20,verbose_name=u"请假类型")
    content = models.CharField(max_length=100,verbose_name=u"请假原因")
    start = models.DateField(verbose_name=u"开始时间")
    end = models.DateField(verbose_name=u"结束时间")
    time = models.DateTimeField(auto_now_add=True,verbose_name=u"申请时间")
    is_active = models.BooleanField(verbose_name=u"是否有效",default=True)

    class Meta:
        ordering = ['-time']

class Travel_apply(models.Model):#出差申请
    business = models.ForeignKey(Business,null=True,blank=True,verbose_name=u"所属机构")
    user = models.ForeignKey(User,null=True,blank=True,verbose_name=u"申请人")
    examine_user = models.ManyToManyField(User,null=True,blank=True,verbose_name=u"审批人",related_name="travel_examine_user")
    topic = models.CharField(max_length=30,verbose_name=u"出差事由")
    content = models.CharField(max_length=30,verbose_name=u"出差地点")
    cost = models.BigIntegerField(verbose_name=u"金额(元)")
    start = models.DateField(verbose_name=u"开始时间")
    end = models.DateField(verbose_name=u"结束时间")
    time = models.DateTimeField(auto_now_add=True,verbose_name=u"申请时间")
    is_active = models.BooleanField(verbose_name=u"是否有效",default=True)

    class Meta:
        ordering = ['-time']

class Read_message(models.Model):

    read_business = models.ForeignKey(Business,null=True,blank=True,verbose_name=u"关联机构")
    read_user = models.ForeignKey(User,null=True,blank=True,verbose_name=u"已读用户")
    model_name = models.CharField(max_length=30,null=True,blank=True,verbose_name=u"模块名")
    record_id = models.IntegerField(null=True,blank=True,verbose_name=u"关联记录的ID")
    read_time = models.DateTimeField(auto_now_add=True,verbose_name=u"查看时间")

    def __unicode__(self):
        return self.record_id

examine_status = (('1',u'通过'),('2',u'驳回'),('3',u'待审核'))

class Examine(models.Model):#审批
    examine_business = models.ForeignKey(Business,null=True,blank=True,verbose_name=u"关联机构")
    examine_user = models.ForeignKey(User,null=True,blank=True,verbose_name=u"审批人")
    examine_status = models.CharField(choices=examine_status,default="3",max_length=1,verbose_name=u"审核结果选择")
    read_status = models.CharField(choices=read_status,default="1",max_length=1,verbose_name=u"读取状态")
    examine_message = models.TextField(null=True,blank=True,verbose_name=u"审批备注")
    is_active = models.BooleanField(verbose_name=u"是否有效",default=True)
    examine_time = models.DateTimeField(null=True,blank=True,verbose_name=u"审批时间")

    class Meta:
        abstract = True

class Cost_examine(Examine):#费用申请审批
    cost_examine = models.ForeignKey(Cost_application,verbose_name=u"关联费用申请")

class Leave_examine(Examine):#请假管理申请审批
    leave_examine = models.ForeignKey(Leave_management,verbose_name=u"关联请假管理申请")

class Travel_examine(Examine):#出差申请审批
    travel_examine = models.ForeignKey(Travel_apply,verbose_name=u"关联出差申请")

class Daily_to_do(models.Model):#每日待办
    todo_user = models.ForeignKey(User,null=True,blank=True,verbose_name=u"待办人")
    topic = models.CharField(max_length=30,verbose_name=u"主题")
    content = models.CharField(max_length=100,verbose_name=u"事件")
    # remark = models.TextField(max_length=300,null=True,blank=True,verbose_name=u"备注")
    remark = HTMLField(null=True,blank=True,verbose_name=u"备注")
    add_time = models.DateTimeField(auto_now_add=True,verbose_name=u"添加时间")
    to_do_time = models.DateTimeField(verbose_name=u"待办事时间")
    is_active = models.BooleanField(verbose_name=u"是否有效",default=True)

    class Meta:
        ordering = ["to_do_time"]

''' 收款管理 '''

class All_Examine(models.Model):#审批
    content_type = models.ForeignKey(ContentType, related_name="content_type_timelines",null=True,blank=True)
    object_id = models.PositiveIntegerField()
    examine = GenericForeignKey('content_type', 'object_id',)
    examine_business = models.ForeignKey(Business,null=True,blank=True,verbose_name=u"关联机构")
    examine_user = models.ForeignKey(User,null=True,blank=True,verbose_name=u"审批人")
    examine_status = models.CharField(choices=examine_status,default="3",max_length=1,verbose_name=u"审核结果选择")
    read_status = models.CharField(choices=read_status,default="1",max_length=1,verbose_name=u"读取状态")
    examine_message = models.TextField(null=True,blank=True,verbose_name=u"审批备注")
    is_active = models.BooleanField(verbose_name=u"是否有效",default=True)
    examine_time = models.DateTimeField(null=True,blank=True,verbose_name=u"审批时间")

    class Meta:
        ordering = ["read_status"]

    '''新建审批时推送到审批人,审批结束时推送到申请人'''
    def save(self, *args, **kwargs):
        is_new = False if self.pk else True
        super(All_Examine, self).save(*args, **kwargs)

        from push.views import push_to_ios, push_to_android
        try:
            application = self.examine
            application_type = self.application_type
            extras={
                    "content_type":'',

code/lvmeng_project-master/templates/admin_erp/admin_customer_list.html
{% extends "erp/base.html" %}
{% block content %}
    <div class="">
        <ol class="breadcrumb">
            <span>当前位置：</span>
            <li class="active">律锰管理</li>
            <li class="active">按角色查看</li>
            <li>客户</li>
        </ol>
        <div class="header-line">
           <!-- START Language list-->
            <h4>客户列表</h4>
        </div>

        <div class="content-table">
            <form action="" method="post" class="form-inline">
                <div class="form-group">
                    <label class="control-label">客户姓名：</label>
                  <div class="col-sm-9">
                     <input type="text" class="form-control" name="customer_name" value="{{customer_name|default:''}}">
                  </div>
               </div>
                <div class="form-group div-wrap">
                  <label class="control-label">电话：</label>
                  <div class="col-sm-9">
                     <input type="text" class="form-control" name="phoneNum" value="{{phoneNum|default:''}}">
                  </div>
               </div>
                <div class="form-group">
                  <label class="control-label">身份证号：</label>
                  <div class="col-sm-9">
                     <input type="text" class="form-control"  name="idNum" value="{{idNum|default:''}}">
                  </div>
               </div>
                <div class="form-group">
                  <div class="col-sm-3 btn-wrap">
                        <input type="submit" value="搜索" class="btn-submit">
                  </div>
                    <div class="col-sm-9">
                    <input type="button" value="数据导出到Excel表格" onclick="download();" title="点击导出数据" class="btn-export">
               </div>
               </div>
                {% comment %}客户姓名：<input type="text" name="customer_name" value="{{customer_name|default:''}}">&nbsp;&nbsp;&nbsp;&nbsp;
                电话：<input type="text" name="phoneNum" value="{{phoneNum|default:''}}">&nbsp;&nbsp;&nbsp;&nbsp;
                身份证号：<input type="text" name="idNum" value="{{idNum|default:''}}">&nbsp;&nbsp;&nbsp;&nbsp;
                <input type="submit" value="搜索">{% endcomment %}
            </form>
        </div>

        <div class="row">
            <div class="col-lg-12 panel-body admin_agent_list table-responsive">
                <table id="example" class="table table-hover excel" style="overflow-x:scroll;white-space:nowrap;">
                    <thead>
                        <tr id="tr_head">
                            <th>序号</th>
                            <th>客户姓名</th>
                            <th>电话</th>
                            <th>性别</th>
                            <th>地址</th>
                            <th>身份证号</th>
                            <th>购买总数量</th>
                            <th>购买总金额/元</th>
                            <th>注册日期</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% load detail_deal %}
                        {% for customer in customers %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td><a class="customer_check" href="/erp/check/?id={{ customer.id }}&type=customer#admin_customers" title="点击查看">{{ customer.name }}</a></td>
                                <td>{{ customer.phoneNum }}</td>
                                <td>{{ customer.get_sex_display }}</td>
                                <td>{{ customer.address }}</td>
                                <td>{{ customer.idCard_num }}</td>
                                {% if customer.count %}
                                    <td><a class="customer_count" href="/erp/admin_product_list/?id={{ customer.id }}&type=admin_product#admin_customers" title="点击查看该客户所购买产品">{{ customer.count }}</a></td>
                                {% else %}
                                    <td><a>{{ customer.count }}</a></td>
                                {% endif %}

                                {% if customer.sum %}
                                    <td style="color:#299A00;">{{ customer.sum }}</td>
                                {% else %}
                                    <td>{{ customer.sum }}</td>
                                {% endif %}
                                <td>{{ customer.register_date|date_str }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>


                </table>
                <div class="nav-pagenation">
                    <ul class="pagination">
                        <li>
                            {% if customers.has_previous %}
                                <a href="?page={{ customers.previous_page_number }}#admin_customers">上一页</a>
                            {% else %}
                                <a href="#" class="disabled">上一页</a>
                            {% endif %}
                        </li>

                        {% for p in page_range %}
                            {% ifequal p customers.number %}
                                <li class="active"><a href="#">{{p}}</a></li>
                            {% else %}
                                <li><a href="?page={{p}}#admin_customers" title="第{{p}}页">{{p}}</a></li>
                            {% endifequal %}
                        {% endfor %}

                        <li>
                            {% if customers.has_next %}
                                <a href="?page={{ customers.next_page_number }}#admin_customers">下一页</a>
                            {% else %}
                                <a href="#" class="disabled">下一页</a>
                            {% endif %}
                        </li>

                        <li>
                            <a href="#">共{{ paginator.count }}条</a>
                        </li>

                        {% ifequal paginator.num_pages 1 %}

                        {% else %}
                            <div class="go-wrap">
                                <form action="">
                                    <input type="text" class="text-go" name="page" value="{{customers.number}}"/>
                                    <input type="submit" class="btn-go" value="跳转"/>
                                </form>
                            </div>
                        {% endifequal %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
<script>

    $(document).ready(function() {
        $('#example').DataTable();
    } );

    $(function(){
        $("th").attr("title","点击排序");
    });

    $(function(){
        $('#example_filter').css('style','display:none');
        $('#example_info').attr('style','display:none');
        $('#example_length').attr('style','display:none');
        $('#example_paginate').attr('style','display:none');
    });

</script>

{% endblock %}

code/lvmeng_project-master/templates/admin_erp/employee_list.html
{% extends "erp/base.html" %}
{% block content %}
    <div class="">
        <div class="">
           <!-- START Language list-->
            <h4 style="color:red;">员工列表</h4>
        </div>
        <div>
            <form action="" method="post">
                员工姓名：<input type="text" name="emp_name" value="{{emp_name|default:''}}">&nbsp;&nbsp;&nbsp;&nbsp;
                电话：<input type="text" name="phoneNum" value="{{phoneNum|default:''}}">&nbsp;&nbsp;&nbsp;&nbsp;
                身份证号：<input type="text" name="idNum" value="{{idNum|default:''}}">&nbsp;&nbsp;&nbsp;&nbsp;
                <input type="submit" value="搜索">
            </form>
        </div>

        <div class="row">
            <div class="col-lg-12 panel-body">
                <table frame=boxrules="all" align="center" border="1" cellspacing="0" cellpadding="0" width="100%;">
                    <tr id="tr_head">
                        <th>姓名</th>
                        <th>电话</th>
                        <th>性别</th>
                        <th>地址</th>
                        <th>身份证号</th>
                        <th>所属机构</th>
                        <th>角色</th>
                        <th>注册日期</th>
                    </tr>

                    {% for emp in employees %}
                        <tr>
                            <th><a href="/erp/check/?id={{ emp.id }}&type=employee" title="点击查看">{{ emp.name }}</a></th>
                            <th>{{ emp.phoneNum }}</th>
                            <th>{{ emp.get_sex_display }}</th>
                            <th>{{ emp.address }}</th>
                            <th>{{ emp.idCard_num }}</th>
                            <th>{{ emp.business }}</th>
                            <th>{{ emp.role }}</th>
                            <th>{{ emp.register_date }}</th>
                        </tr>
                    {% endfor %}

                </table>
            </div>
        </div>
    </div>
{% endblock %}

code/lvmeng_project-master/templates/admin_erp/redister_business_add.html
{% extends "erp/base.html" %}
{% block content %}
    <div class="">
        <ol class="breadcrumb">
            <span>当前位置：</span>
            <li class="active">律锰管理</li>
            <li>添加客户机构</li>
        </ol>
        <div class="header-line">
           <!-- START Language list-->
            <h4>{{message}}</h4>
        </div>

        {% if messages %}
            {% for message in messages %}
                {% if forloop.last %}
                    <div class="message" style="text-align:center;margin-bottom:10px;font-size:20px;color:#E53E4D;"><img style="width:20px;height:20px;" src="/static/img/cancel.gif">{{ message }}</div>
                {% endif %}
            {% endfor %}
        {% endif %}

        <input style="display:none;" name="check_remark" id="check_remark" value="{{ check_remark }}">
        <input style="display:none;" name="check_remark" id="remark" value="{{ remark }}">
        <input style="display:none;" id="reject_id" value="{{ id }}">
        <div class="row">
            <div class="col-lg-12 panel-body">
                <form action="/erp/business_redister_examine/" method="post" role="form" name="form" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% load crispy_forms_tags %}
                        {% crispy form %}
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
<script>


    $(function(){
        $("#id_address").before("<form name='shareip' action='' method='' id='city_form'><select class='select form-control' name='province' id='s1' style='width:180px;display: inline-block;'><option></option></select>&nbsp;&nbsp;&nbsp;<select class='select form-control' name='city' id='s2' style='width:180px;display: inline-block;'><option></option></select>&nbsp;&nbsp;&nbsp;<select class='select form-control' name='town' id='s3' style='width:180px;display: inline-block;'><option></option></select></form>");        $("#id_address").css("margin-top","10px");
    });

    $(function(){
        var mark = $("#check_remark").val();
        if(mark){
            $("#city_form").css("display","none");
        }
        $("#s3").change(function(){
            var province = $("#s1").find("option:selected").val();
            var city = $("#s2").find("option:selected").val();
            var town = $("#s3").find("option:selected").val();
            if(province == city){
                $("#id_address").val(province+town)
            }else{
                $("#id_address").val(province+city+town)
            }

        });
    });

    $(function(){
        var mark = $("#id_phoneNum").val();
        var remark = $("#remark").val();

        $("#id_email").after("<span id='span_email' style='font-size:18px;color:red;display:none;'>该邮箱已存在,请重新输入</span>");

        if(remark=="true"){
            $("#id_email").attr({"readonly":true});
        }
    });

    $(function(){
        $("#id_email").change(function(){
            var str = $("#id_email").val()
            $.ajax({
            type:"get",
            url:"/erp/valid_phone/",
            data:{'str':str},
            success:function(data){
                    if(data.result == "false"){
                        $("#span_email").css("display","");
                    }else{
                        $("#span_email").css("display","none");
                    }
                }
        });
        });
    });


$(function(){
    $("#button-id-save").click(function(){
        var id = $("#reject_id").val();
        $.ajax({
        type:"get",
        url:"/erp/rejection_reason/",
        data:{"id":id},
        success:function(html){
               $.webox({
                   height:500,
                   width:800,
                   bgvisibel:true,
                   title:'驳回原因',
                   html:html,
                });
            }
        });



        <!--var a = confirm("您确定要驳回该机构注册申请吗?");-->
        <!--if(a==true)-->
         <!--{-->
            <!--document.form.action="/erp/business_redister_examine/?type=cancel&id={{ id }}#redister_business";-->
            <!--document.form.submit();-->
         <!--}-->
    });
});

</script>
{% endblock %}

code/lvmeng_project-master/templates/admin_erp/rejection_reason.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <form method="post" action="/erp/business_redister_examine/?type=cancel&id={{ id }}#redister_business">
        <textarea style="height:420px;width:798px;" id="reject_reason" name="reject_reason">

        </textarea>
        <div style="border:1px solid #CCCCCC;height:53px;margin-top:-8px;">
        <input type="submit" value="确定" style="background-color:#0092E6;margin-left:10px;width:100px;font-size:20px;margin-top:10px">
            </div>
    </form>
</body>
</html>