code/lvmeng_project-master/erp/urls.py
#coding:utf-8
from django.conf.urls import url
from django.views.generic.base import RedirectView

from . import views,views2
from erp import tests1 as tests
urlpatterns = [
    url(r'^product_process/$', views.product_process),#产品操作
    url(r'^position_list/$',views.position_list),#职位列表
    url(r'^position_add_modify/$',views.position_add_modify),#新增/修改职位
    url(r'^business_process/$',views.business_process),#新增客户机构

    url(r'^business_list/$',views.business_list),#客户机构列表
    url(r'^business_password_change/(?P<user_id>\d+)/$',views.business_password_change),#强制修改密码
    url(r'^agent_process/$',views.agent_process),#新增员工
    url(r'^agent_list/$',views.agent_list),#员工列表
    url(r'^product_list/$',views.product_list),#产品列表
    url(r'^check/$',views.check),#查看

    url(r'agent_customer_allot/$',views2.agent_customer_allot),#删除理财师进行客户分配

    # -------------------------下面将要去除（测试用）------------------------------------------
    url(r'^customer_list/$',views.customer_list),#客户列表
    url(r'^customer_add/$',views.customer_add),#新增客户
    # ---------------------------------------------------------------

    # ---------------------------just for admin--------------------------------------
    url(r'^admin_agent_list/$',views2.agent_role),#按员工角色查看
    url(r'^agent_customers/$',views2.agent_customers),#根据员工查看下面的客户
    url(r'^admin_product_list/$',views2.admin_purchase_list),#查看客户的所有购买
    url(r'^purchases_list/$',views2.purchases_list),#查看客户的所有购买
    url(r'^admin_customers/$',views2.admin_customers),#查看所有的客户
    url(r'^redister_customers/$',views2.redister_customers),#查看所有的注册客户
    url(r'^admin_business_product/$',views.admin_business_product),#查看机构所有的产品
    url(r'^business_redister_list/$',views.business_redister_list),#律锰查看注册申请列表
    url(r'^business_redister_examine/$',views.business_redister_examine),#律锰审核注册申请
    # ---------------------------just for admin--------------------------------------

    url(r'^picture_logos/$',views2.business_logos),#添加机构图片信息
    url(r'^business_announcement_list/$',views2.business_announcement_list),#查看机构公告列表

    url(r'^agent_add_product/$',views2.agent_add_product),#理财师添加客户所购买的产品信息/添加的列表
    url(r'^agent_product_list/$',views2.agent_product_list),#理财师添加客户所购买的产品信息的列表

    url(r'^income_inquiry/$',views2.income_inquiry),#财务查看购买的产品信息的列表

    url(r'^customer_business_search/$',views2.customer_business_search),#用户选择机构显示相对应的信息
    url(r'^show_product_by_type/$',views2.show_product_by_type),

    url(r'^financial_headlines/$',views2.financial_headlines),#金融头条列表
    url(r'^headline_add_modify/$',views2.headline_add_modify),#新增/修改金融头条

    url(r'^modify_business_base_info/$',views2.modify_business_base_info),#修改机构基本信息
    url(r'^show_business_base_info/$',views2.show_business_base_info),#机构基本信息

    url(r'^username_change/$',views2.username_change),#修改用户名(账号)

    url(r'^release_base_64/$',views2.release_base_64),


    url(r'^valid_phone/$',tests.valid_phone),#验证手机号是否存在
    url(r'^valid_email/$',tests.valid_email),#验证邮箱是否存在
    url(r'^check_new_message/$',tests.check_new_message),#检测是否有新消息
    url(r'^get_position_permission/$',tests.get_position_permission),#获取对应职位的权限

    #机构轮播图
    url(r'^business_carousel_list_delete/$',views.business_carousel_list_delete),
    url(r'^business_carousel_add/$',views.business_carousel_add),

    url(r'^no_permission/$',views.no_permission),

    url(r'^mail_list/$',views.mail_list),#通讯录

    #机构注册
    url(r'^business_redister/$',views.business_redister.as_view()),#注册第一步
    url(r'^business_redister_detail/$',views.business_redister_detail),#注册第二步
    url(r'^business_redister_save/$',views.business_redister_save),#保存注册信息
    # url(r'^register_success/$',views.register_success),#注册成功

    #客户注册
    url(r'^person_redister/$',views.person_redister),#客户注册
    url(r'^valid_code/$',tests.valid_code),#验证码验证

    url(r'^online_chat/$',views.online_chat),#在线聊天
    url(r'^save_user_message/$',views.save_user_message),#保存聊天信息
    url(r'^chat_user_message/$',views.chat_user_message),#获取聊天信息
    url(r'^chat_logo_message_remind/$',views.chat_logo_message_remind),#获取所有未读信息
    url(r'^message_control/$',views.message_control),#将每个人的信息控制在100条


    url(r'^rejection_reason/$',views.rejection_reason),#机构注册申请驳回原因














    # url(r'', views.employee_list),#所有的员工
]

code/lvmeng_project-master/lvmeng/urls.py
from django.conf.urls import include, url,handler404,handler500
from django.contrib import admin
from django.conf.urls.static import static
from lvmeng import settings
from django.views.generic.base import RedirectView
from django.views.decorators.csrf import csrf_exempt
from rest_framework.authtoken import views
from erp import views2
import web_customer.views
from erp.tests import test_login

handler404 = "erp.views.page_not_found"
handler500 = "erp.views.page_error"


urlpatterns = [
    #admin
    url(r'admin/', include(admin.site.urls)),

    #homepage
    url(r'^$', web_customer.views.homePage),
    url(r'^ie8', web_customer.views.homePage_ie8),
    url(r'^mobi/$', web_customer.views.mobile_homePage),

    #login
    url(r'customer_login/$', web_customer.views.customer_login),
    url(r'login/$', views2.account_login),

    url(r'test/$', test_login),#test for login

    #inner app
    url(r'^api/', include('api.urls')),
    url(r'^agent_api/', include('agent_api.urls')),
    url(r'^message_api/', include('message_api.urls')),
    url(r'^push/', include('push.urls')),
    url(r'^erp/', include('erp.urls')),
    url(r'^oa/', include('oa.urls')),
    url(r'^web_customer/', include('web_customer.urls')),
    url(r'^mobi/', include('mobi.urls')),
    url(r'^invest/', include('investment.urls')),

    #outer app
    url(r'^tinymce/',include('tinymce.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),#TODO:need to remove csrf_exempt in production
    # url(r'^rest-auth/', include('rest_auth.urls')),
    url(r'^api-token-auth/', views.obtain_auth_token),
    url(r'^captcha/', include('captcha.urls')),

    #account
    # url(r'^password_change/', 'django.contrib.auth.views.password_change', {'post_change_redirect': '/password_change_done/'}),
    url(r'^password_change/', 'django.contrib.auth.views.password_change', {'post_change_redirect': '/'}),
    url(r'^password_change_done/', 'django.contrib.auth.views.password_change_done'),
    # url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/accounts/login/'}),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
    url(r'^accounts/', include('registration.backends.default.urls')),

    # url(r'admin/', include(admin.site.urls)),
    # url(r'^$', include('web_customer.urls')),
    # url(r'^web_customer/', include('web_customer.urls')),
    # url(r'^mobi/$', web_customer.views.mobile_homePage),
    # url(r'^announcement/$', web_customer.views.announcement),
    # url(r'^tinymce/',include('tinymce.urls')),
]

#todo has to be removed in production
#this will serve media files during development environment, otherwise files uploaded by users won't be recognized
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

code/lvmeng_project-master/oa/urls.py
#coding:utf-8
#employee_distribution

from django.conf.urls import url
from . import views,views2

urlpatterns = [
    url(r'^employee_distribution/$', views.employee_distribution),#
    url(r'^employee_position/$', views.employee_position),#
    url(r'^ajax_name/$', views.ajax_name),#根据ID获取姓名
    url(r'^employee_history_position/$', views.employee_history_position),#根据ID获取姓名
    url(r'^employee_history_position_days/$', views.employee_history_position_days),#根据ID获取姓名

    url(r'^announcement_employee/$', views.announcement_employee),#通知公告(面向员工)
    url(r'^announcement_add_modify/$', views.announcement_add_modify),#通知公告新增/修改/

    url(r'^daily_work/$', views.daily_work),#工作汇报列表/删除
    url(r'^daily_work_add_modify/$', views.daily_work_add_modify),#工作汇报新增/

    url(r'^cost_application/$', views.cost_application),#费用列表和删除
    url(r'^cost_add_modify/$', views.cost_add_modify),#费用新增
    url(r'^edit_examine/$', views.edit_examine),#编写费用审核
    url(r'^cost_examine/$', views2.cost_examine),#查看费用审核结果
    url(r'^daily_work_examine/$', views2.daily_work_examine),#查看工作汇报审核结果
    url(r'^examine_list/$', views2.examine_list),#查看自己的所有审核列表

    url(r'^leave_management/$', views.leave_management),#请假列表和删除
    url(r'^leave_add_modify/$', views.leave_add_modify),#请假新增
    # url(r'^edit_leave_examine/$', views.edit_leave_examine),#编写请假审核
    url(r'^leave_examine/$', views2.leave_examine),#查看请假审核结果
    # url(r'^leave_examine_list/$', views2.leave_examine_list),#查看自己的请假审核列表

    url(r'^travel_apply/$', views.travel_apply),#出差列表和删除
    url(r'^travel_add_modify/$', views.travel_add_modify),#出差新增
    # url(r'^edit_travel_examine/$', views.edit_travel_examine),#编写出差审核
    url(r'^travel_examine/$', views2.travel_examine),#查看出差审核结果
    # url(r'^travel_examine_list/$', views2.travel_examine_list),#查看自己的出差审核列表

    url(r'^daily_todo_list/$', views2.daily_todo_list),#每日待办列表/删除
    url(r'^daily_todo_add_modify/$', views2.daily_todo_add_modify),#每日待办事件新增和修改

    url(r'^check_table/$', views2.check_table),#
    url(r'^check_time_setting/$', views2.check_time_setting),#

    # url(r'^read_message/$', views.read_message),#添加已读记录







]

code/lvmeng_project-master/push/urls.py
#! /usr/bin/env python
#coding:utf-8

from django.conf.urls import url, include
from api.rest_framework import APNSDeviceAuthorizedViewSet, GCMDeviceAuthorizedViewSet, JPUSHDeviceAuthorizedViewSet
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'device/apns', APNSDeviceAuthorizedViewSet)
router.register(r'device/gcm', GCMDeviceAuthorizedViewSet)
router.register(r'device/jpush', JPUSHDeviceAuthorizedViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),

]

code/lvmeng_project-master/api/models.py
#coding:utf-8
from django.db import models

from erp.models import *
from tinymce.models import HTMLField

# Create your models here.
class Version(models.Model):#版本号
    version = models.CharField(max_length=10,null=False,blank=False,verbose_name=u'版本号')
    url = models.URLField(verbose_name=u'下载链接')
    context = models.CharField(max_length=100,null=True,blank=True,verbose_name=u'版本信息')
    date = models.DateTimeField(blank=True, null=True, verbose_name=u"添加日期")

    def __unicode__(self):
        return self.version


class Headline(models.Model):#金融头条,,按照时间排序
    add_date = models.DateField(blank=True, null=True, verbose_name=u"添加日期",auto_now_add=True)
    register_date = models.DateTimeField(blank=True, null=True, verbose_name=u"时间")
    title = models.CharField(max_length=30,null=False,blank=False, default='',verbose_name=u'标题',unique=True)
    picture = models.ImageField(upload_to='api/headlines/', verbose_name=u"简图", blank=True,null=True)
    # context = models.TextField(max_length=15000,null=True,blank=True,verbose_name=u'内容')
    context = HTMLField(null=True,blank=True,verbose_name=u'内容')
    url = models.URLField(null=True,blank=True,verbose_name=u'详情链接')
    read_num = models.PositiveIntegerField(null=True,blank=True,default=0,verbose_name=u"阅读次数")

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['-register_date']

#删除新闻头条的图片
def on_delete(sender, instance, **kwargs):
    instance.picture.delete(save=False)

models.signals.post_delete.connect(on_delete, sender=Headline)


class Comment(models.Model): #金融头条评论
    headline = models.ForeignKey(Headline, verbose_name=u'新闻头条')
    user = models.ForeignKey(User, null=True, blank=True, verbose_name=u'用户')
    praise = models.ManyToManyField(User, related_name="praise", null=True, blank=True, verbose_name=u'点赞')
    content = models.CharField(max_length=1000, verbose_name=u'评论内容')
    time = models.DateTimeField(auto_now_add=True, verbose_name=u'评论时间')
    is_valid = models.BooleanField(default=True, verbose_name=u'是否有效')

    class Meta:
        ordering = ['-time']


class History_Checkin(models.Model):#签到记录
    user = models.ForeignKey(User,null=True,blank=True,verbose_name=u'用户')
    register_date = models.DateField(blank=True, null=True, verbose_name=u"签到日期", auto_now_add=True)
    abscissa = models.CharField(max_length=30,verbose_name=u"横坐标")#经度
    ordinate = models.CharField(max_length=30,verbose_name=u"纵坐标")#纬度

    def __unicode__(self):
        return self.user.first_name

    class Meta:
        ordering = ['-register_date']


class Checkin(models.Model):#签到统计
    user = models.OneToOneField(User,null=True,blank=True,verbose_name=u'用户', unique=True)
    latest_date = models.DateField(blank=True, null=True, verbose_name=u"最后签到日期")
    points = models.PositiveIntegerField(blank=True, null=True, verbose_name=u"积分")
    continuous_days = models.PositiveIntegerField(blank=True, null=True, verbose_name=u"连续登录天数")
    abscissa = models.CharField(max_length=30,blank=True, null=True,verbose_name=u"横坐标")#经度
    ordinate = models.CharField(max_length=30,blank=True, null=True,verbose_name=u"纵坐标")#纬度

    def __unicode__(self):
        return self.user.first_name

    class Meta:
        ordering = ['-latest_date']


class ValidSecond(models.Model):#手机验证码有效时间
    seconds = models.IntegerField(blank=True, null=True, verbose_name=u"验证码有效时间")


purpose = (('0',u'注册验证'),('1',u'修改密码'),('2',u'信息修改'))
class VerificationCode(models.Model):#手机验证码
    phoneNum = models.CharField(max_length=18,null=False,blank=False,verbose_name=u'电话')
    code = models.CharField(max_length=18,null=False,blank=False,verbose_name=u'验证码')
    purpose = models.CharField(choices=purpose, max_length=18,null=True,blank=True,verbose_name=u'用途')
    register_date = models.DateTimeField(blank=False, null=False, verbose_name=u"添加日期")

    class Meta:
        ordering = ['-register_date']


class EmailValidSecond(models.Model):#邮箱验证码有效时间
    seconds = models.IntegerField(blank=True, null=True, verbose_name=u"验证码有效时间")


class EmailCode(models.Model):#邮箱验证码
    email = models.EmailField(max_length=100,null=False,blank=False,verbose_name=u'邮箱')
    code = models.CharField(max_length=18,null=False,blank=False,verbose_name=u'验证码')
    register_date = models.DateTimeField(blank=False, null=False, verbose_name=u"添加日期")

    class Meta:
        ordering = ['-register_date']


class Collection(models.Model):#用户收藏
    customer = models.ForeignKey(Customer,null=True,blank=True,verbose_name=u'用户')
    product = models.ForeignKey(Product,null=True,blank=True,verbose_name=u'产品')
    register_time = models.DateTimeField(blank=True, null=True, verbose_name=u"收藏时间", auto_now_add=True)

    class Meta:
        ordering = ['-register_time']
        unique_together = ('customer', 'product')


class Attention(models.Model):#用户关注
    customer = models.ForeignKey(Customer,null=True,blank=True,verbose_name=u'用户')
    product = models.ForeignKey(Product,null=True,blank=True,verbose_name=u'产品')
    register_time = models.DateTimeField(blank=True, null=True, verbose_name=u"关注时间", auto_now_add=True)

    class Meta:
        ordering = ['-register_time']
        unique_together = ('customer', 'product')


point_types = (('0',u'手机认证'),('1',u'实名认证'),('2',u'邮箱认证'),
               ('3',u'每日签到'),('4',u'连续7天签到'),('5',u'新增客户'),
               ('6', u'分享转发'),('7', u'OA处理'),('8', u'新增产品'))
class Point(models.Model):#用户额外添加的积分
    type = models.CharField(choices=point_types, max_length=10, verbose_name=u'积分类型', unique=True)
    points = models.IntegerField(verbose_name=u"积分")
    max_points = models.IntegerField(blank=True, null=True, verbose_name=u"封顶积分")

code/lvmeng_project-master/templates/erp/agent_process.html
{% extends "erp/base.html" %}
{% block content %}
    <div class="">
        <ol class="breadcrumb">
            <span>当前位置：</span>
            <li class="active">员工管理</li>
            <li>查看员工</li>
            {% if message %}
                <li>{{ message }}</li>
            {% else %}
                <li>员工基本信息</li>
            {% endif %}
        </ol>
        <div class="header-line">
           <!-- START Language list-->
            {% if message %}
                <h4>{{ message }}</h4>
            {% else %}
                <h4>员工基本信息</h4>
            {% endif %}
        </div>

        {% if messages %}
            {% for message in messages %}
                {% if forloop.last %}
                    <div class="message" style="text-align:center;margin-bottom:10px;font-size:20px;color:#E53E4D;"><img style="width:20px;height:20px;" src="/static/img/cancel.gif">{{ message }}</div>
                {% endif %}
            {% endfor %}
        {% endif %}

        <input style="display:none;" name="check_remark" id="check_remark" value="{{ check_remark }}">
        <!--<input style="display:none;" name="check_remark" id="remark" value="{{ remark }}">-->
        <input style="display:none;" name="" id="picture" value="{{ agent.avatar|default:'' }}">
        <div class="row">
            <div class="col-lg-12 panel-body">
                <form action="/erp/agent_process/?agent_id={{ agent_id }}#agent_process" method="post" role="form" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% load crispy_forms_tags %}
                        {% crispy form %}
                        <!--<input type="submit" onclick="if(confirm('确定要保存以上信息吗？')==false)return false;" value="保存">-->
                </form>

            <div id="show_customer" class="form-group">
                <label for="id_graduated_school" class="control-label ">拥有客户：</label>
                <div class="controls ">
                    <span>{{ count }}</span>
                    <ul>
                        {% for customer in customers %}
                            {% if request.user.is_superuser %}
                                <li><a class="customer_check" href="/erp/check/?id={{ customer.id }}&type=customer#admin_agent_list">{{ customer.name }}</a></li>
                            {% else %}
                                <li><a class="customer_check" href="/erp/check/?id={{ customer.id }}&type=customer">{{ customer.name }}</a></li>
                            {% endif %}
                        {% endfor %}

                    </ul>
                </div>
            </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
<script>



    $(function(){
        $("#id_address").before("<form name='shareip' action='' method='' id='city_form'><select class='select form-control' name='province' id='s1' style='width:180px;display: inline-block;'><option></option></select>&nbsp;&nbsp;&nbsp;<select class='select form-control' name='city' id='s2' style='width:180px;display: inline-block;'><option></option></select>&nbsp;&nbsp;&nbsp;<select class='select form-control' name='town' id='s3' style='width:180px;display: inline-block;'><option></option></select></form>");
        $("#id_address").css("margin-top","10px");
        $("#id_address").css("margin-bottom","10px");
    });

    $(function(){
        var mark = $("#check_remark").val();
        if(mark){
            $("#city_form").css("display","none");
        }
        $("#s3").change(function(){
            var province = $("#s1").find("option:selected").val();
            var city = $("#s2").find("option:selected").val();
            var town = $("#s3").find("option:selected").val();
            if(province == city){
                $("#id_address").val(province+town)
            }else{
                $("#id_address").val(province+city+town)
            }
        });
    });

    $(function(){
        var mark = $("#id_phoneNum").val();
        var remark = $("#remark").val();
        if(mark==""){
            $("#div_id_phoneNum").after("<div class='form-group'><label class='control-label'>初始密码<span style='color:red;'>*</span></label><div class='controls'><input name='password' id='password' placeholder='输入初始密码' autocomplete='off' class='form-control' value='' style='width:180px;'/></div></div>");
        }
        if(remark=="true"){
            $("#id_phoneNum").attr({"readonly":true});
        }

        <!--$("#id_phoneNum").after("<span id='span_phoneNum' style='font-size:18px;color:red;display:none;'>该号码已存在,请重新输入</span>");-->
        <!--$("#id_email").after("<span id='span_email' style='font-size:18px;color:red;display:none;'>该邮箱已存在,请重新输入</span>");-->

        $('#id_position option').each(function(){
            if($(this).val() == ''){
                $(this).html('请选择');
            }
        });

    });

    <!--$(function(){-->
        <!--$("#id_phoneNum").change(function(){-->
            <!--var str = $("#id_phoneNum").val()-->
            <!--$.ajax({-->
            <!--type:"get",-->
            <!--url:"/erp/valid_phone/",-->
            <!--data:{'str':str},-->
            <!--success:function(data){-->
                    <!--if(data.result == "false"){-->
                        <!--$("#span_phoneNum").css("display","");-->
                    <!--}else{-->
                        <!--$("#span_phoneNum").css("display","none");-->
                    <!--}-->
                <!--}-->
            <!--});-->
        <!--});-->
    <!--});-->

    <!--$(function(){-->
        <!--$("#id_email").change(function(){-->
            <!--var str = $("#id_email").val()-->
            <!--$.ajax({-->
            <!--type:"get",-->
            <!--url:"/erp/valid_email/",-->
            <!--data:{'str':str},-->
            <!--success:function(data){-->
                    <!--if(data.result == "false"){-->
                        <!--$("#span_email").css("display","");-->
                    <!--}else{-->
                        <!--$("#span_email").css("display","none");-->
                    <!--}-->
                <!--}-->
        <!--});-->
        <!--});-->
    <!--});-->

    $(function(){
        $("#id_position").change(function(){
            var position_id = $('#id_position option:selected').val();
            $.ajax({
            type:"get",
            url:"/erp/get_position_permission/",
            data:{'position_id':position_id},
            success:function(html){
                   $("#div_id_permissions").html(html);
                }
            });
        });
    });

    $(function(){
        $("#id_avatar").after("<input type='text' style='display:none;' name='base_1' id='base_1'/>");
    });

    $(document).ready(function(e){
      $('#id_avatar').customFile({
            type : 'image',
            image : {
                crop	: true,
                cropSize: [100,100],
                preview : {
                    display: true,
                    maxWidth: 5000,
                    maxHeight: 5000,
                }
            },
            filePicker : '<h5>点击上传图片</h5>',
      });
    });

     $(function(){
        $("#submit-id-save").click(function(){
            set_base_input();
        });
     });

     $(function(){
        if($("#picture").val()){
            var src = "/media/"+$("#picture").val()
            $("#div_id_avatar").before("<div id='show_avatar'><img style='height:140px;' title='当前图片' src="+src+" /></div>");
        }
     });

</script>
{% endblock %}

code/lvmeng_project-master/templates/erp/business_password_change.html
{% extends "erp/base.html" %}

{% block content %}
    <div class="">
        <ol class="breadcrumb">
            <span>当前位置：</span>
            <li class="active">律锰管理</li>
            <li>{{ message }}</li>
        </ol>
        <div class="header-line">
           <!-- START Language list-->
            <h4 align="center">{{ message }}</h4>
        </div>

        <div>
             <div class="tips">
               <!-- START Language list-->
                <p align="center">[系统自动发送邮件有可能在垃圾邮件中，请注意检查]</p>
            </div>
            <div class="panel-body">
                <form align="center" onsubmit="return checkPassword();" action="/erp/business_password_change/{{ user_id }}/?type={{ type }}" method="post" role="form" id="pwd_form">

                    <span id="notice_error" style="font-size:20px;color:red;display:none;">两次输入的密码不一样</span><br>
                    <div class="error">
                        <h5 style="color:red;">{{ error }}</h5>
                    </div>

                    <div class="form-sheet">
                        <input type="password" name="password" id="password" placeholder="输入新密码" class="form-control">
                        <input type="password" name="password2" id="password2"  placeholder="确认新密码" class="form-control">
                        <!--<input onclick="checkPassword();" type="button" value="保存" class="form-control btn-change-pwd">-->
                        <input  type="submit" value="保存" class="form-control btn-change-pwd">
                    </div>


                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script>
        function checkPassword(){
            var pass1 = $("#password").val();
            var pass2 = $("#password2").val();
            if(pass1!=pass2){
                $("#notice_error").css("display","");
                return false;
            }
        }
    </script>
{% endblock %}

code/lvmeng_project-master/templates/erp/email_change.html
{% extends "erp/base.html" %}
{% block content %}
    <div class="">
        <ol class="breadcrumb">
            <span>当前位置：</span>
            <li class="active">律锰管理</li>
            <li>{{ message }}</li>
        </ol>
        <div class="header-line">
           <!-- START Language list-->
            <h4 align="center">{{ message }}</h4>
        </div>

        <div>
             <div class="tips">
               <!-- START Language list-->
                <p align="center">[系统自动发送邮件有可能在垃圾邮件中，请注意检查]</p>
            </div>
            <div class="panel-body">
                <form align="center" action="/erp/username_change/?user_id={{ user.id }}&type={{ redi_type }}" method="post" role="form" id="pwd_form">

                    <div class="error">
                        <h5 id="notice" style="color:red;">{{ error }}</h5>
                    </div>

                    <div class="form-sheet">
                        <input type="text" name="" readonly value="{{ user.username }}" placeholder="修改的邮箱" class="form-control">
                        <input type="text" name="username" id="username" placeholder="输入新邮箱" class="form-control" required onchange="check_email(this.value);">
                        <input type="text" placeholder="新登录密码" class="form-control"  type="text" name="password" required>
                        <input type="submit" value="保存" class="form-control btn-change-pwd">
                    </div>


                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
<script>
function check_email(strEmail)
      {
            if(strEmail)
          {
            if(strEmail.search(/^\w+((-\w+)|(\.\w+))*\@[A-Za-z0-9]+((\.|-)[A-Za-z0-9]+)*\.[A-Za-z0-9]+$/)!= -1){
              $("#notice").css("display","none");
              }
           else{
              $("#notice").html("邮箱格式不对!");
              $("#notice").css("display","");
              }
          }
      }

</script>

{% endblock %}

code/lvmeng_project-master/templates/erp/no_permission.html
{% extends "erp/base.html" %}
{% block content %}
<!--<div align="center" style="margin-top:300px;font-size:50px;">-->
    <!--<div id="aa" ></div>-->
    <!--<h2 style="color:red;">对不起，您无访问权限</h2>-->
<!--</div>-->
    <div class="">
        <img src="/static/img/gis/fangwenquanxian.png" style="margin-top:30px;margin-left:30px;"/>
    </div>
{% endblock %}
{% block script %}
<script>
    <!--function clock() {-->
        <!--i = i - 1;-->
        <!--document.getElementById("aa").innerHTML = "将在" + i + "秒后自动为您跳转!";-->
        <!--if (i > 0)setTimeout("clock();", 1000);-->
        <!--else location.href="/";-->
    <!--}-->
    <!--var i = 3;//时间:秒-->
    <!--clock();-->
</script>
{% endblock %}

code/lvmeng_project-master/templates/erp/online_chat_detail.html
{% load detail_deal %}
      <div class="chat01_content">
        {% for message in all_messages %}
        <div class="message_box mes3" style="display: block;">
          <div class="message clearfix">
            <div class="user-logo">
            <img style="width:50px;height:50px;" src="{{ message.sender.agent.avatar|check_picture }}" onerror="this.src='/static/img/default.png'"></div>
            <div class="wrap-text">
              <h6 class="clearfix" style="color:#0E6EB8">{{ message.sender }}&nbsp;&nbsp;&nbsp;{{ message.send_time|date_str }}</h6>
              <div>{{ message.content }}</div></div>
            <div style="clear:both;"></div>
          </div>
        </div>
        {% endfor %}

      </div>